"""Módulo de autenticación y autorización."""

from app.core.auth.dependencies import (
    ApiKeyAuth,
    CurrentTenant,
    CurrentUser,
    OptionalUser,
    RequireAdmin,
    RequireMember,
    RequireOwner,
    SessionDep,
    get_current_tenant,
    get_current_user,
    get_session,
    get_tenant_from_api_key,
    require_role,
    user_to_response,
)
from app.core.auth.router import router as auth_router
from app.core.auth.schemas import (
    ApiKeyCreateRequest,
    ApiKeyListResponse,
    ApiKeyResponse,
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    TokenResponse,
    UserResponse,
)
from app.core.auth.security import (
    create_access_token,
    create_refresh_token,
    decode_token,
    generate_api_key,
    hash_api_key,
    hash_password,
    verify_api_key,
    verify_password,
)
from app.core.auth.service import (
    ApiKeyNotFoundError,
    AuthError,
    InactiveUserError,
    InvalidCredentialsError,
    InvalidTokenError,
    TenantNotFoundError,
    UserAlreadyExistsError,
    UserNotFoundError,
    create_api_key,
    list_api_keys,
    login_user,
    refresh_access_token,
    register_user,
    revoke_api_key,
    verify_api_key_from_header,
)

__all__ = [
    # Dependencies
    "SessionDep",
    "CurrentUser",
    "OptionalUser",
    "CurrentTenant",
    "RequireAdmin",
    "RequireOwner",
    "RequireMember",
    "ApiKeyAuth",
    "get_session",
    "get_current_user",
    "get_current_tenant",
    "get_tenant_from_api_key",
    "require_role",
    "user_to_response",
    # Router
    "auth_router",
    # Schemas
    "RegisterRequest",
    "LoginRequest",
    "RefreshRequest",
    "TokenResponse",
    "UserResponse",
    "ApiKeyCreateRequest",
    "ApiKeyResponse",
    "ApiKeyListResponse",
    # Security
    "hash_password",
    "verify_password",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "generate_api_key",
    "hash_api_key",
    "verify_api_key",
    # Service
    "register_user",
    "login_user",
    "refresh_access_token",
    "create_api_key",
    "list_api_keys",
    "revoke_api_key",
    "verify_api_key_from_header",
    # Exceptions
    "AuthError",
    "InvalidCredentialsError",
    "UserAlreadyExistsError",
    "UserNotFoundError",
    "TenantNotFoundError",
    "InactiveUserError",
    "InvalidTokenError",
    "ApiKeyNotFoundError",
]
